Repository FuelLabs/fuels-wallet, pull requests merged in 2022-12, with the labels that each got.

#345 fix(app): creation of services obj on store
  packages/app/src/store.tsx
  packages/app/src/systems/Account/machines/accountMachine.tsx
  packages/app/src/systems/Home/pages/Home/Home.stories.tsx
  packages/store/src/createStore.tsx
  packages/store/src/types.ts
Labels: bug

#362 feat: add account form component
  packages/app/src/systems/Account/components/AccountForm/AccountForm.stories.tsx
  packages/app/src/systems/Account/components/AccountForm/AccountForm.test.tsx
  packages/app/src/systems/Account/components/AccountForm/AccountForm.tsx
  packages/app/src/systems/Account/components/AccountForm/index.tsx
  packages/app/src/systems/Account/components/index.tsx
  packages/app/src/systems/Account/hooks/useAccountForm.ts
Labels: enhancement

#340 feat: account list screen
  .changeset/brave-windows-hear.md
  packages/app/playwright/mocks/database.ts
  packages/app/src/routes.tsx
  packages/app/src/store.tsx
  packages/app/src/systems/Account/components/AccountItem/AccountItem.tsx
  packages/app/src/systems/Account/components/AccountList/AccountList.stories.tsx
  packages/app/src/systems/Account/components/AccountList/AccountList.test.tsx
  packages/app/src/systems/Account/components/AccountList/AccountList.tsx
  packages/app/src/systems/Account/components/BalanceWidget/BalanceWidget.test.tsx
  packages/app/src/systems/Account/components/BalanceWidget/BalanceWidget.tsx
  packages/app/src/systems/Account/events.tsx
  packages/app/src/systems/Account/hooks/useAccount.tsx
  packages/app/src/systems/Account/index.tsx
  packages/app/src/systems/Account/machines/accountMachine.test.ts
  packages/app/src/systems/Account/machines/accountMachine.tsx
  packages/app/src/systems/Account/pages/Accounts/Accounts.stories.tsx
  packages/app/src/systems/Account/pages/Accounts/Accounts.tsx
  packages/app/src/systems/Account/pages/Accounts/index.tsx
  packages/app/src/systems/Account/pages/index.tsx
  packages/app/src/systems/Account/routes.tsx
  packages/app/src/systems/Account/services/account.ts
  packages/app/src/systems/Core/types.ts
  packages/app/src/systems/DApp/hooks/useSignatureRequest.tsx
  packages/app/src/systems/DApp/hooks/useTransactionRequest.tsx
  packages/app/src/systems/DApp/pages/ConnectionRequest/ConnectionRequest.tsx
  packages/app/src/systems/DApp/pages/SignatureRequest/SignatureRequest.tsx
  packages/app/src/systems/DApp/pages/TransactionRequest/TransactionRequest.tsx
  packages/app/src/systems/Faucet/components/FaucetDialog.tsx
  packages/app/src/systems/Faucet/hooks/useOpenFaucet.ts
  packages/app/src/systems/Home/pages/Home/Home.tsx
  packages/app/src/systems/Home/pages/Receive/Receive.tsx
  packages/app/src/systems/Settings/hooks/useSettings.ts
  packages/app/src/systems/Sidebar/components/Sidebar/Sidebar.tsx
  packages/app/src/systems/SignUp/pages/WalletCreated/index.tsx
  packages/app/src/systems/Transaction/hooks/useTxOutputs.tsx
  packages/types/src/accounts.ts
Labels: screen
