Repository FuelLabs/fuels-wallet, pull requests merged in 2023-02, with the labels that each got.

#513 chore: improve project tooling
  .eslintignore
  .lintstagedrc
  .prettierignore
  .prettierrc
  .vscode/extensions.json
  packages/app/src/systems/DApp/machines/signMachine.tsx
  packages/config/index.js
  packages/docs/docs/browser-support.mdx
  packages/docs/src/styles/docsearch/_variables.css
  packages/docs/src/styles/docsearch/modal.css
  packages/docs/src/styles/docsearch/style.css
  packages/docs/src/styles/index.css
  packages/fuelhat/commands/index.mjs
  packages/fuelhat/commands/start.mjs
  packages/fuelhat/commands/stop.mjs
  packages/fuelhat/docker/docker-compose.yml
  packages/fuelhat/index.mjs
  packages/fuelhat/utils/createEnv.mjs
  pnpm-workspace.yaml
  scripts/build-website.mjs
  scripts/builds/utils.mjs
  scripts/gh-pages-preview.mjs
Labels: refactor

#543 fix: home redirect, source code link and code import
  packages/docs/docs/contributing/running-locally.mdx
  packages/docs/docs/how-to-use.mdx
  packages/docs/examples/Connect.tsx
  packages/docs/examples/CurrentAccount.tsx
  packages/docs/examples/ListAccounts.tsx
  packages/docs/examples/SignMessage.tsx
  packages/docs/examples/Transfer.tsx
  packages/docs/src/components/Link.tsx
  packages/docs/src/lib/code-import.ts
  packages/docs/src/pages/index.tsx
Labels: bug, documentation

#548 refactor: clean popup service and add extra check on connection
  packages/app/src/systems/CRX/background/communication.ts
  packages/app/src/systems/CRX/background/services/BackgroundService.ts
  packages/app/src/systems/CRX/background/services/PopUpService.ts
  packages/app/src/systems/CRX/background/services/types.ts
  packages/app/src/systems/CRX/utils/popups.ts
  packages/app/src/systems/DApp/hooks/useConnectRequest.tsx
  packages/app/src/systems/DApp/hooks/useSignatureRequest.tsx
  packages/app/src/systems/DApp/hooks/useTransactionRequest.tsx
  packages/app/src/systems/DApp/machines/connectMachine.test.ts
  packages/app/src/systems/DApp/machines/connectMachine.ts
  packages/app/src/systems/DApp/machines/signMachine.test.tsx
  packages/app/src/systems/DApp/machines/signMachine.tsx
  packages/app/src/systems/DApp/machines/transactionMachine.test.tsx
  packages/app/src/systems/DApp/machines/transactionMachine.tsx
Labels: refactor

#587 docs: add assets and add asset to api
  .changeset/healthy-ligers-press.md
  packages/app/src/systems/CRX/background/services/BackgroundService.ts
  packages/docs/docs/api.mdx
  packages/sdk/src/Fuel.test.ts
  packages/sdk/src/__mock__/Fuel.ts
Labels: documentation
