Repository FuelLabs/fuels-wallet, pull requests merged in 2024-01, with the labels that each got.

#1044 docs: add changeset documentation
  packages/docs/docs/contributing/guide.mdx
Labels: docs

#1045 fix: check supported network version
  .changeset/nice-lizards-reply.md
  packages/app/package.json
  packages/app/src/config.ts
  packages/app/src/systems/CRX/background/services/BackgroundService.ts
  packages/app/src/systems/Network/__mocks__/networks.ts
  packages/app/src/systems/Network/services/network.ts
  pnpm-lock.yaml
Labels: bug

#1043 fix: throw error when asset name is undefined
  .changeset/rich-starfishes-join.md
  packages/app/src/systems/Asset/services/assets.ts
Labels: bug

#1062 chore: upgrading `fuels` to `salamander` RC
  .changeset/many-falcons-camp.md
  packages/app/jest.setup.ts
  packages/app/package.json
  packages/app/src/systems/Transaction/__mocks__/transaction.tsx
  packages/app/src/systems/Transaction/machines/transactionMachine.test.tsx
  packages/connections/package.json
  packages/docs/package.json
  packages/e2e-contract-tests/package.json
  packages/e2e-contract-tests/src/contracts/contracts/factories/CustomAssetAbi__factory.ts
  packages/react/package.json
  packages/sdk/jest.setup.ts
  packages/sdk/package.json
  packages/sdk/src/FuelWalletLocked.ts
  packages/test-utils/package.json
  packages/types/package.json
  pnpm-lock.yaml
Labels: chore
